'use strict';

export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const TOGGLE_RECOMMENDATIONS = 'TOGGLE_RECOMMENDATIONS';
export const TOGGLE_NUTRITION_FACTS = 'TOGGLE_NUTRITION_FACTS';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const RESET_ALL_SETTINGS = 'RESET_ALL_SETTINGS';
