export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const INCREMENT_DAY = 'INCREMENT_DAY';
export const DECREMENT_DAY = 'DECREMENT_DAY';
export const SELECT_DAY = 'SELECT_DAY';
export const SEARCH_DAY = 'SEARCH_DAY';
export const FETCH_MEAL_REQUEST = 'FETCH_MEAL_REQUEST';
export const FETCH_MEAL_FAILED = 'FETCH_MEAL_FAILED';
export const FETCH_MEAL_RESULT = 'FETCH_MEAL_RESULT';
export const MORE_SEARCH_RESULT = 'MORE_SEARCH_RESULT';
export const SEARCH_MEAL_INFO = 'SEARCH_MEAL_INFO';
export const ADD_MEAL = 'ADD_MEAL';
export const EDIT_MEAL = 'EDIT_MEAL';
export const DELETE_MEAL = 'DELETE_MEAL';
export const SAVE_MEAL = 'SAVE_MEAL';
export const ADD_GROCERY_ITEM = 'ADD_GROCERY_ITEM';
export const EDIT_GROCERY_ITEM = 'EDIT_GROCERY_ITEM';
export const REMOVE_GROCERY_ITEM = 'REMOVE_GROCERY_ITEM';
export const TOGGLE_GROCERY_ITEM = 'TOGGLE_GROCERY_ITEM';
export const NEW_EMPTY_LIST = 'NEW_EMPTY_LIST';
export const NEW_POPULATED_LIST = 'NEW_POPULATED_LIST';
export const SAVE_LIST = 'SAVE_LIST';
export const EDIT_LIST = 'EDIT_LIST';
export const REMOVE_LIST = 'REMOVE_LIST';
export const SAVE_PREFERENCES = 'SAVE_PREFERENCES';
export const EDIT_PREFERENCES = 'EDIT_PREFERENCES';
export const REMOVE_PREFERENCES = 'REMOVE_PREFERENCES';
export const NEW_PREFERENCES = 'NEW_PREFERENCES';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const RESET_PREFERENCES = 'RESET_PREFERENCES';
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const RESET_ALL_SETTINGS = 'RESET_ALL_SETTINGS';
export const SET_ANALYSIS_FILTER = 'SET_ANALYSIS_FILTER';
export const AnalysisFilters = {
  FILTER_DAY: 'FILTER_DAY',
  FILTER_WEEK: 'FILTER_WEEK',
  FILTER_YEAR: 'FILTER_YEAR',
  FILTER_ALL: 'FILTER_ALL',
};
