'use strict';

export const ADD_INTOLERANCE_REQUEST = 'ADD_INTOLERANCE_REQUEST';
export const ADD_INTOLERANCE_SUCCESS = 'ADD_INTOLERANCE_SUCCESS';
export const ADD_INTOLERANCE_FAILURE = 'ADD_INTOLERANCE_FAILURE';
export const REMOVE_INTOLERANCE_REQUEST = 'REMOVE_INTOLERANCE_REQUEST';
export const REMOVE_INTOLERANCE_SUCCESS = 'REMOVE_INTOLERANCE_SUCCESS';
export const REMOVE_INTOLERANCE_FAILURE = 'REMOVE_INTOLERANCE_FAILURE';
export const RESET_INTOLERANCES_REQUEST = 'RESET_INTOLERANCES_REQUEST';
export const RESET_INTOLERANCES_SUCCESS = 'RESET_INTOLERANCES_SUCCESS';
export const RESET_INTOLERANCES_FAILURE = 'RESET_INTOLERANCES_FAILURE';
