'use strict';

export const ADD_INTOLERANCE_REQUEST = 'ADD_INTOLERANCE_REQUEST';
export const ADD_INTOLERANCE_SUCCESS = 'ADD_INTOLERANCE_SUCCESS';
export const ADD_INTOLERANCE_FAILURE = 'ADD_INTOLERANCE_FAILURE';
export const REMOVE_INTOLERANCE_REQUEST = 'REMOVE_INTOLERANCE_REQUEST';
export const REMOVE_INTOLERANCE_SUCCESS = 'REMOVE_INTOLERANCE_SUCCESS';
export const REMOVE_INTOLERANCE_FAILURE = 'REMOVE_INTOLERANCE_FAILURE';
