'use strict';

export const SET_ANALYSIS_FILTER = 'SET_ANALYSIS_FILTER';
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const FETCH_USER_MEAL_DATA_REQUEST = 'FETCH_USER_MEAL_DATA_REQUEST';
export const FETCH_USER_MEAL_DATA_SUCCESS = 'FETCH_USER_MEAL_DATA_SUCCESS';
export const FETCH_USER_MEAL_DATA_FAILURE = 'FETCH_USER_MEAL_DATA_FAILURE';
export const AnalysisFilters = {
  FILTER_DAY: 'FILTER_DAY',
  FILTER_WEEK: 'FILTER_WEEK',
  FILTER_YEAR: 'FILTER_YEAR',
  FILTER_ALL: 'FILTER_ALL',
};
