'use strict';

export const ADD_GROCERY_ITEM_REQUEST = 'ADD_GROCERY_ITEM_REQUEST';
export const ADD_GROCERY_ITEM_SUCCESS = 'ADD_GROCERY_ITEM_SUCCESS';
export const ADD_GROCERY_ITEM_FAILURE = 'ADD_GROCERY_ITEM_FAILURE';
export const REMOVE_GROCERY_ITEM_REQUEST = 'REMOVE_GROCERY_ITEM_REQUEST';
export const REMOVE_GROCERY_ITEM_SUCCESS = 'REMOVE_GROCERY_ITEM_SUCCESS';
export const REMOVE_GROCERY_ITEM_FAILURE = 'REMOVE_GROCERY_ITEM_FAILURE';
export const TOGGLE_GROCERY_ITEM_REQUEST = 'TOGGLE_GROCERY_ITEM_REQUEST';
export const TOGGLE_GROCERY_ITEM_SUCCESS = 'TOGGLE_GROCERY_ITEM_SUCCESS';
export const TOGGLE_GROCERY_ITEM_FAILURE = 'TOGGLE_GROCERY_ITEM_FAILURE';
export const NEW_EMPTY_LIST_REQUEST = 'NEW_EMPTY_LIST_REQUEST';
export const NEW_EMPTY_LIST_SUCCESS = 'NEW_EMPTY_LIST_SUCCESS';
export const NEW_EMPTY_LIST_FAILURE = 'NEW_EMPTY_LIST_FAILURE';
export const REMOVE_LIST_REQUEST = 'REMOVE_LIST_REQUEST';
export const REMOVE_LIST_SUCCESS = 'REMOVE_LIST_SUCCESS';
export const REMOVE_LIST_FAILURE = 'REMOVE_LIST_FAILURE';
