'use strict';

export const RECEIVE_USER_FAILURE = 'RECEIVE_USER_FAILURE';
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const SAVE_USER_REQUEST = 'SAVE_USER_SUCCESS';
export const SAVE_USER_REQUEST = 'SAVE_USER_FAILURE';
